spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${profile:dev}
    gateway:
      routes:
        - id: apicatalog
          uri: lb://CATALOG-SERVICE
          predicates:
           - Path=/catalog/**
        - id: apimovie
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**